name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' 

    - name: Install dependencies
      run: npm ci

    - name: Run linters
      run: npm run lint
      if: ${{ success() }}

    - name: Run tests
      run: npm run test
      if: ${{ success() }}

    - name: Build application
      run: npm run build
      if: ${{ success() }}
